export class ExcelRowExportGps {
    // A
    serialNumber?: string;
    // B
    shipperName?: string;
    // C
    shipperPhone?: string;
    // D
    shipperAddress?: string;
    // E
    orderID?: string;
    // F
    consigneeName?: string;
    // G
    consigneePhone?: string;
    // H
    consigneeCell?: string;
    // I
    consigneePostalCode?: string;
    // J
    consigneeAddress1?: string;
    // K
    consigneeAddress2?: string;
    // L
    customSID?: string;
    // M
    consigneeMemo?: string;
    // N
    consigneeTypeID?: string;
    // O
    consigneeCustomTypeID?: string;
    // P
    volume1?: string;
    // Q
    volume2?: string;
    // R
    volume3?: string;
    // S
    weight?: string;
    // T
    weightTypeID?: string;
    // U
    boxCount?: string;
    // V
    priceTypeID?: string;
    // W
    itemDescription?: string;
    // X
    itemBrand?: string;
    // Y
    itemPrice?: string;
    // Z
    itemQuantity?: string;
    // AA
    hSCode?: string;
}
